# Copyright (C) 2020-2026 Aditya Shakya <adi1090x@gmail.com>
#
# Hyprland configuration : Output --------------------------

# The general config of a monitor looks like this:

## --- Variables ---
$LAPTOP_RES = 2880x1800@60.00
$LAPTOP_SCALE = 1.8

# monitor = name, resolution, position, scale
#
# To list all available monitors (active and inactive): `hyprctl monitors all`
# monitor = ,preferred,auto,1

# HiDPI Laptop
monitor = eDP-1,$LAPTOP_RES,0x0,$LAPTOP_SCALE

# Disable a monitor
#monitor = eDP-1, disable

# Example : External monitor, mode: 1920x1080, position: right of laptop, scale: 1.5, gaps of 20 each side, rotated 90d
monitor = HDMI-A-1,preferred,auto,1
#monitor = HDMI-A-1,addreserved,20,20,20,20
#monitor = HDMI-A-1,transform,1
#workspace = HDMI-A-1,2

# ---
 
# Example : Laptop screen, mode: 1920x1080, scale: 1, gaps of 10 each side
#monitor = eDP-1,1920x1080@60,0x0,1
#monitor = eDP-1,addreserved,10,10,10,10
#monitor = eDP-1,transform,0
#workspace = eDP-1,1

# ---

# Monitor v2 : Alternative syntax
#monitorv2 {
#    output = HDMI-A-1
#    mode = 1920x1080@60
#    position = 0x0
#    scale = 1
#    transform = 0
#    addreserved = 20,20,20,20
#}

# --------- workspace to Monitor ----------
# Monitor 1 handles Workspaces 1 through 3
workspace = 1, monitor:eDP-1
workspace = 2, monitor:eDP-1
workspace = 3, monitor:eDP-1

# Monitor 2 handles Workspaces 4 through 9
workspace = 4, monitor:HDMI-A-1
workspace = 5, monitor:HDMI-A-1
workspace = 6, monitor:HDMI-A-1
workspace = 7, monitor:HDMI-A-1
workspace = 8, monitor:HDMI-A-1
workspace = 9, monitor:HDMI-A-1


# Lock screen on lid close (no suspend)
bindl=,switch:on:Lid Switch, exec, pidof hyprlock || hyprlock

# Optional: turn off display on lid close
# bindl=,switch:on:Lid Switch, exec, hyprctl dispatch dpms off

# Turn display on when lid opens
bindl=,switch:off:Lid Switch, exec, hyprctl dispatch dpms on

