plugin:dynamic-cursors {
    enabled = true

    # Sets the cursor behaviour, supports these values:
    # tilt    - tilt the cursor based on x-velocity
    # rotate  - rotate the cursor based on movement direction
    # stretch - stretch the cursor shape based on direction and velocity
    # none    - do not change the cursors behaviour
    mode = none

    # Minimum angle difference in degrees after which the shape is changed
    # Smaller values are smoother, but more expensive for hw cursors
    threshold = 2

    # Configure shake to find (similar to MacOS / KDE)
    shake {
        enabled = true
        nearest = true
        threshold = 4.0
        base = 4.0
        speed = 2.0
        influence = 0.0
        limit = 0.0
        timeout = 2000
        effects = false
        ipc = false
    }

    # Hyprcursor support for high-res magnified cursors
    hyprcursor {
        nearest = true
        enabled = true
        resolution = -1
        fallback = clientside
    }
}
