version = 3

[var]
  Filler = '<#808080>─</>'

[secondary_prompt]
  template = ' ❯❯ '
  foreground = 'magenta'
  background = 'transparent'

[transient_prompt]
  template = ' ❯ '
  foreground = '#ffffff'
  background = 'transparent'
  foreground_templates = ['{{if gt .Code 0 }}red{{end}}', '{{if eq .Code 0 }}magenta{{end}}']
  newline = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '╭─[<#55ff55>{{ .UserName }}</><#ff5555>@</><#ffff55>{{ .HostName }}</>]{{ .Var.Filler }}'
    type = 'session'
    style = 'plain'

  [[blocks.segments]]
    template = '<#ffffff>[</><b>{{ .Path }}</b><#ffffff>]</>'
    foreground = '#6395ee'
    type = 'path'
    style = 'plain'

    [blocks.segments.properties]
      style = 'full'

  [[blocks.segments]]
    template = '{{ .Var.Filler }}<#ffffff>(</>{{ .HEAD }}{{ if .Staging.Changed }}<#00AA00> ● {{ .Staging.String }}</>{{ end }}{{ if .Working.Changed }}<#D75F00> ● {{ .Working.String }}</>{{ end }}<#ffffff>)</>'
    foreground = '#e0f8ff'
    type = 'git'
    style = 'plain'

    [blocks.segments.properties]
      branch_icon = ' '
      fetch_status = true
      fetch_upstream_icon = true

[[blocks]]
  type = 'prompt'
  alignment = 'right'
  filler = '<#808080>─</>'

  [[blocks.segments]]
    template = '{{ if gt .Code 0 }}{{ .Code }}{{ .Var.Filler }}{{ end }}'
    foreground = '#FF3333'
    type = 'status'
    style = 'plain'

    [blocks.segments.properties]
      always_enabled = true

  [[blocks.segments]]
    template = '<#ffffff>(</>{{ if .PackageManagerIcon }}{{ .PackageManagerIcon }} {{ end }}{{ .Full }}<#ffffff>)</>'
    foreground = '#3C873A'
    type = 'node'
    style = 'plain'

    [blocks.segments.properties]
      fetch_package_manager = true
      npm_icon = ' <#cc3a3a> </> '
      yarn_icon = ' <#348cba> </>'

  [[blocks.segments]]
    template = '<#ffffff>(</>{{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }} {{ end }}{{ .Full }}{{ end }}<#ffffff>)</>'
    foreground = '#FFE873'
    type = 'python'
    style = 'plain'

  [[blocks.segments]]
    template = '<#ffffff>(</>{{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}<#ffffff>)</>'
    foreground = '#ec2729'
    type = 'java'
    style = 'plain'

  [[blocks.segments]]
    template = '<#ffffff>(</>{{ if .Unsupported }} {{ else }}{{ .Full }}{{ end }}<#ffffff>)</>'
    foreground = '#0d6da8'
    type = 'dotnet'
    style = 'plain'

  [[blocks.segments]]
    template = '<#ffffff>(</>{{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}<#ffffff>)</>'
    foreground = '#06aad5'
    type = 'go'
    style = 'plain'

  [[blocks.segments]]
    template = '<#ffffff>(</>{{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}<#ffffff>)</>'
    foreground = '#925837'
    type = 'rust'
    style = 'plain'

  [[blocks.segments]]
    template = '<#ffffff>(</>{{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}<#ffffff>)</>'
    foreground = '#055b9c'
    type = 'dart'
    style = 'plain'

  [[blocks.segments]]
    template = '<#ffffff>(</>{{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}<#ffffff>)</>'
    foreground = '#ce092f'
    type = 'angular'
    style = 'plain'

  [[blocks.segments]]
    template = '<#1e293b>(</>{{ if .Error }}{{ .Error }}{{ else }}Nx {{ .Full }}{{ end }}<#1e293b>)</>'
    foreground = '#ffffff'
    type = 'nx'
    style = 'plain'

  [[blocks.segments]]
    template = '<#ffffff>(</>{{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}<#ffffff>)</>'
    foreground = '#359a25'
    type = 'julia'
    style = 'plain'

  [[blocks.segments]]
    template = '<#ffffff>(</>{{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}<#ffffff>)</>'
    foreground = '#9c1006'
    type = 'ruby'
    style = 'plain'

  [[blocks.segments]]
    template = '<#ffffff>(</>{{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}<#ffffff>)</>'
    foreground = '#5398c2'
    type = 'azfunc'
    style = 'plain'

  [[blocks.segments]]
    template = '<#ffffff>(</>{{.Profile}}{{if .Region}}@{{.Region}}{{end}}<#ffffff>)</>'
    foreground = '#faa029'
    type = 'aws'
    style = 'plain'

  [[blocks.segments]]
    template = '<#ffffff>(</>{{.Context}}{{if .Namespace}} :: {{.Namespace}}{{end}}<#ffffff>)</>'
    foreground = '#316ce4'
    type = 'kubectl'
    style = 'plain'

  [[blocks.segments]]
    template = '<#ffffff>(</>{{ if .WSL }}WSL at {{ end }}{{.Icon}}<#ffffff> )</>{{ .Var.Filler }}'
    foreground = '#ffffff'
    type = 'os'
    style = 'plain'

    [blocks.segments.properties]
      linux = '<#ffffff> </>'
      macos = '<#ffffff> </>'
      windows = '<#ffffff> </>'

  [[blocks.segments]]
    template = '<#ffffff>[</>{{ if not .Error }}{{ .Icon }}{{ .Percentage }}{{ end }}{{ .Error }}%<#ffffff>]─</>'
    foreground = '#ffffff'
    type = 'battery'
    style = 'plain'
    foreground_templates = ['{{if eq "Charging" .State.String}}#40c4ff{{end}}', '{{if eq "Discharging" .State.String}}#FFFB38{{end}}', '{{if eq "Full" .State.String}}#33DD2D{{end}}']

    [blocks.segments.properties]
      charged_icon = ' '
      charging_icon = ' '
      discharging_icon = ' '

  [[blocks.segments]]
    template = '<#ffffff>[</> {{ .CurrentDate | date .Format }}<#ffffff>]</>'
    foreground = '#55ffff'
    type = 'time'
    style = 'plain'

    [blocks.segments.properties]
      time_format = '_2,15:04'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    template = '╰─➤'
    type = 'text'
    style = 'plain'

  [[blocks.segments]]
    template = '{{ if .Root }}# {{ else }}$ {{ end }}'
    foreground = '#ecf7fa'
    type = 'status'
    style = 'plain'
    foreground_templates = ['{{ if .Root }}#FF9248{{ end }}', '{{ if gt .Code 0 }}#ef5350{{ end }}']

    [blocks.segments.properties]
      always_enabled = true

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    template = '{{ .FormattedMs }}  '
    foreground = 'yellow'
    background = 'transparent'
    type = 'executiontime'
    style = 'plain'

    [blocks.segments.properties]
      style = 'austin'
      threshold = 3000
